### ISSUE TITLE
installation instructions

### ISSUE THREAD

**Issue by VeteranGamer** [withgallantry/OneForAll#5]
Hi,

I'm a complete NOOB....

what are the instructions for this to be installed....
i'm hoping for something as easy and along the lines of the instructions as they are here

https://github.com/Helder1981/OneForAll

the Helder version has a few issues that i'm hoping this edited/revision will resolve

Thank you

**Comment by Helder1981** [comment]
I have a new install.sh file for this version, the only thing you need to do if using a Pi 3A/B is change input from **udev** to **linuxraw** in the RetroArch using a keyboard is good for this then it will no longer be required. Just follow the instructions as in my link but use this install.sh file.
[install.zip](https://github.com/withgallantry/OneForAll/files/4013511/install.zip)
Oh and you will want the Binary files of the program, not the ones that are uncompiled. Here is the link: https://github.com/withgallantry/OneForAllBinary

Follow the images on this site on how to find the setting I am talking about.
https://www.retro-programming.de/retro-welt-2/hardware/raspberry-pi-als-emulator-retropie/retropie-controller-einrichten/#manuell

One important thing to remember also in the keysKeyboard.cfg file the OSD has to be a key declared above in the [KEYS] section for example I am using **KEY_U=19 #Just defined to work** and my OSD is as follows **OSD_SHOW=19**. This pin is not used for anything controls wise but needs to be declared to be used for the OSD, hope this helps.

**Comment by gh0st08** [comment]
Forgive my ignorance as I'm learning all of this as well... Are you using your instructions but with withgallantry's git for the clone, then uploading the install zip in that repository, and then following your directions for the install.sh? and ignoring the install/build directions that withgallantry posted all together?  And where do the Binary files you linked come into play? I have been stuck for about a month now trying to my device working. I see the OSD show up in emulation station, but have zero controls despite numerous attempts at uploading the codes and changing settings.  Ive tried copying the git to a new repository and changing the keyKeyboard.cfg to match my wiring, ive tried cloning the original git directly to the pi and configuring through ssh, Im just not sure if im doing the whole process wrong or what.  Any help would be extremely appreciated, thank you.

**Comment by Helder1981** [comment]
Clone his github the one I linked above in my post into your Pi, then download my install.zip and extract it into the new directory created on the Pi home Directory it should be called OneForAll.

Then go to my github linked in the original Post and follow the directions there to install it. 

**If you are using a Pi 3A/3B then you need to edit the controller settings which are easy to follow using the last link in my previous post on how to get to the proper screen to change the setting required or the controls will not work in any emulator.**

Hope this is clearer now. If you do not change the settings I just mentioned in the bold text your controls will likely not work.

**Comment by gh0st08** [comment]
Helder thank you for the response.  I cloned the binary git to my pi.  repository created was OneForAllBinary, I renamed to OneForAll.  Copied your install.sh file to that folder via finder, file is showing as in OneForAll folder from terminal.  Copied your directions into terminal, "sudo chmod 755 /home/pi/OneForAll/install.sh" - no issue.  But when I enter "sudo /home/pi/OneForAll/./install.sh" - I get "sudo: unable to execute /home/pi/OneForAll/./install.sh: No such file or directory"

update: after erasing it and starting over, i was able to follow the install instructions. OSD shows up and some buttons are working, though not correctly since ive wired my differently.  the only issue I am still running into is changing the keysKeyboard.cfg file.  As soon as I make a change to it and restart the pi nothing works, no OSD and no keys.  any thoughts?

**Comment by VeteranGamer** [comment]
apologies...
but i doing something wrong...
or my NOOB brain is kicking into overdrive, as I just cant get this to work

<a href="https://imgur.com/XrQ9oyB"><img src="https://i.imgur.com/XrQ9oyB.jpg" title="source: imgur.com" /></a>
I facing the same issue gh0st08
but i've tried everything (well what i expect is everything)

I've used FileZilla to manual transfer over the OneForAllBinary
and I've done
$ git clone --recursive https://github.com/withgallantry/OneForAllBinary.git

I've also transferred over the install.sh using FileZilla

I've tried to excute this

$ sudo chmod 755 /home/pi/OneForAll/install.sh
$ sudo /home/pi/OneForAll/./install.sh

with Putty and on the build itself by exiting emulationstation

I've deleted.... and re-added
I've also started off with a fresh build

still at a loss

any help with be greatly appreciated

Thanks

**Comment by withgallantry** [comment]
I'll speak to Helder and we'll get an easier installation method set up.

**Comment by withgallantry** [comment]
> Helder thank you for the response. I cloned the binary git to my pi. repository created was OneForAllBinary, I renamed to OneForAll. Copied your install.sh file to that folder via finder, file is showing as in OneForAll folder from terminal. Copied your directions into terminal, "sudo chmod 755 /home/pi/OneForAll/install.sh" - no issue. But when I enter "sudo /home/pi/OneForAll/./install.sh" - I get "sudo: unable to execute /home/pi/OneForAll/./install.sh: No such file or directory"
> 
> update: after erasing it and starting over, i was able to follow the install instructions. OSD shows up and some buttons are working, though not correctly since ive wired my differently. the only issue I am still running into is changing the keysKeyboard.cfg file. As soon as I make a change to it and restart the pi nothing works, no OSD and no keys. any thoughts?

The numbers are GPIO numbers, not pin numbers, could you show me what you edited it to and I'll take a look?

**Comment by withgallantry** [comment]
> apologies...
> but i doing something wrong...
> or my NOOB brain is kicking into overdrive, as I just cant get this to work
> 
> [![](https://camo.githubusercontent.com/7b10c5453fd7e7358430fcc5e05bb770c62571de/68747470733a2f2f692e696d6775722e636f6d2f587251396f79422e6a7067)](https://imgur.com/XrQ9oyB)
> I facing the same issue gh0st08
> but i've tried everything (well what i expect is everything)
> 
> I've used FileZilla to manual transfer over the OneForAllBinary
> and I've done
> $ git clone --recursive https://github.com/withgallantry/OneForAllBinary.git
> 
> I've also transferred over the install.sh using FileZilla
> 
> I've tried to excute this
> 
> $ sudo chmod 755 /home/pi/OneForAll/install.sh
> $ sudo /home/pi/OneForAll/./install.sh
> 
> with Putty and on the build itself by exiting emulationstation
> 
> I've deleted.... and re-added
> I've also started off with a fresh build
> 
> still at a loss
> 
> any help with be greatly appreciated
> 
> Thanks

It looks like the file doesn't exist, I'd try `cd /home/pi/OneForAll` and then `ls` to see what's in that folder. If install is there then `sudo ./install.sh` should do it.

**Comment by VeteranGamer** [comment]
thanks for getting back so quick...

i've tried
"cd /home/pi/OneForAll and then ls to see what's in that folder. If install is there then sudo ./install.sh"

<a href="https://imgur.com/OkZ7m1d"><img src="https://i.imgur.com/OkZ7m1d.jpg" title="source: imgur.com" /></a>


still no joy

**Comment by withgallantry** [comment]
Try making it executable, even though it looks ok.
`sudo chmod +x install.sh`
Then try executing it again.

**Comment by VeteranGamer** [comment]
unfortunately....

still no luck....

i must be doing something wrong....
as gh0st08 had a similar issue....
but by deleting and reinstalling/re-trying
he was some how able to get it to work (not sure what the actual fix was)

the Helder1981/OneForAll works...
but only if you have Analog stick enabled...
as in Keyboard the controls stop working once out of the emulation station menus/selection

even though the build I'm working on currently doesn't have a analog stick...
setting it to analog enabled isn't a major issue and you can kinda bear living with a analog stick symbol/icon at the top (even though you don't have one)

but also more importantly I needed to have the OSD show assigned to another button 
kinda committed to that now as I've already added one to the build
Helder1981/OneForAll doesn't allow you to change the OSD show it has to be assigned to the hoykey/select
(this is my experience)


baffled

**Comment by withgallantry** [comment]
You can definitely do those things, I think it'll be better if I create an installation to help solve the issues. I'll work on it from today.

**Comment by gh0st08** [comment]
> > Helder thank you for the response. I cloned the binary git to my pi. repository created was OneForAllBinary, I renamed to OneForAll. Copied your install.sh file to that folder via finder, file is showing as in OneForAll folder from terminal. Copied your directions into terminal, "sudo chmod 755 /home/pi/OneForAll/install.sh" - no issue. But when I enter "sudo /home/pi/OneForAll/./install.sh" - I get "sudo: unable to execute /home/pi/OneForAll/./install.sh: No such file or directory"
> > update: after erasing it and starting over, i was able to follow the install instructions. OSD shows up and some buttons are working, though not correctly since ive wired my differently. the only issue I am still running into is changing the keysKeyboard.cfg file. As soon as I make a change to it and restart the pi nothing works, no OSD and no keys. any thoughts?
> 
> The numbers are GPIO numbers, not pin numbers, could you show me what you edited it to and I'll take a look?

Hey thanks for the response and help. I am using gpio numbering not the pin numbers.  Here's my pin setup: [KEYS]
KEY_LEFT=23 #Left DPAD
KEY_RIGHT=18 #Right DPAD
KEY_DOWN=4 #Down DPAD
KEY_UP=15 #Up DPAD
KEY_LEFTCTRL=19 #A Button
KEY_LEFTALT=26 #B Button
KEY_Z=13 #X Button
KEY_X=6 #Y Button
KEY_G=7 #L1 Button
KEY_H=12 #R1 Button
KEY_SPACE=17 #Select Button
KEY_ENTER=22 #Start Button
KEY_B=21 #L2 Button
KEY_N=20 #R2 Button

[COMBOS]
KEY_ESC=6, 13

[HOTKEYS]
OSD_SHOW=11
VOLUME_UP=15
VOLUME_DOWN=4
TOGGLE_WIFI=23
TOGGLE_BLE=13
TOGGLE_JOYSTICK=19

[JOYSTICK]
ENABLED=False
DEADZONE=300
VCC=1600

for some reason now though when I have install.sh copied in the folder my retropie wont boot up.  When I remove it, emulation station loads just fine.  Add it again, not even use the commands Helder posted to execute it, emulation station wont load.  Ill have to troubleshoot to see if I can get this working again and then see if the keyconfig will work.

**Comment by gh0st08** [comment]
> unfortunately....
> 
> still no luck....
> 
> i must be doing something wrong....
> as gh0st08 had a similar issue....
> but by deleting and reinstalling/re-trying
> he was some how able to get it to work (not sure what the actual fix was)
> 
> the Helder1981/OneForAll works...
> but only if you have Analog stick enabled...
> as in Keyboard the controls stop working once out of the emulation station menus/selection
> 
> even though the build I'm working on currently doesn't have a analog stick...
> setting it to analog enabled isn't a major issue and you can kinda bear living with a analog stick symbol/icon at the top (even though you don't have one)
> 
> but also more importantly I needed to have the OSD show assigned to another button
> kinda committed to that now as I've already added one to the build
> Helder1981/OneForAll doesn't allow you to change the OSD show it has to be assigned to the hoykey/select
> (this is my experience)
> 
> baffled

The method I used to get it working earlier, before it stopped loading emulation station all together was this:
from terminal and ssh: nano
then copied and pasted the contents of install.sh file to terminal.
saved as install.sh

after rebooting I was able to run the install.sh command from Helder.  I dont know why it worked after I did this, but hopefully it'll work for you as well.  I need to figure out why emulation station isn't loading now with the install.sh in the OneForAll folder.  Hopefully we can both get this working, Id imagine its something we're doing wrong on our end since we are both beginners when it comes to this.

**Comment by VeteranGamer** [comment]
> 
> 
> You can definitely do those things, I think it'll be better if I create an installation to help solve the issues. I'll work on it from today.

thank you....
really appreciate it

I think it may have to something do with the install.sh Helder linked 
https://github.com/withgallantry/OneForAll/files/4013511/install.zip

especially if the way Gh0st08 got it to work was to recreate that file from scratch

I personally haven't tried it yet (being a NOOB didn't even think of it)....
which I planed to do over the weekend....

fingers crossed that it will work... and I don't face the other issues that he is now presented with

.

**Comment by VeteranGamer** [comment]
> The method I used to get it working earlier, before it stopped loading emulation station all together was this:
> from terminal and ssh: nano
> then copied and pasted the contents of install.sh file to terminal.
> saved as install.sh
> 
> after rebooting I was able to run the install.sh command from Helder. I dont know why it worked after I did this, but hopefully it'll work for you as well. I need to figure out why emulation station isn't loading now with the install.sh in the OneForAll folder. Hopefully we can both get this working, Id imagine its something we're doing wrong on our end since we are both beginners when it comes to this.

both beginners...
I dont know about that....
I not even on beginner level yet...
you were still clued up enough to recreate the install.sh (which i feel is the culprit in all this)
I wouldn't even know how to at this point (gonna be doing some googling)

two things ( i may have missed them)
what RPi are you using.....
also what version of Retropie is it

mine is a RPi3A+ with Retropie 4.5.1

.

**Comment by Helder1981** [comment]
The install is just a bunch of single commands you can run yourself if you just copy paste each command one at a time and let it do it's thing. You will need to be in the OneForAll directory though and it needs to be named OneForAll and exactly in this spelling with capital letters as shown, Linux is picky in spelling.

**Comment by gh0st08** [comment]
> > The method I used to get it working earlier, before it stopped loading emulation station all together was this:
> > from terminal and ssh: nano
> > then copied and pasted the contents of install.sh file to terminal.
> > saved as install.sh
> > after rebooting I was able to run the install.sh command from Helder. I dont know why it worked after I did this, but hopefully it'll work for you as well. I need to figure out why emulation station isn't loading now with the install.sh in the OneForAll folder. Hopefully we can both get this working, Id imagine its something we're doing wrong on our end since we are both beginners when it comes to this.
> 
> both beginners...
> I dont know about that....
> I not even on beginner level yet...
> you were still clued up enough to recreate the install.sh (which i feel is the culprit in all this)
> I wouldn't even know how to at this point (gonna be doing some googling)
> 
> two things ( i may have missed them)
> what RPi are you using.....
> also what version of Retropie is it
> 
> mine is a RPi3A+ with Retropie 4.5.1
> 
> .

I'm using a 3B same version of retropie.  I tried troubleshooting: wiped SD card and started from scratch. I disconnected all wires from pi and ran a gpio function test- all working.  Checked continuity of all control wires.  Reconnected, reverified continuity. Loaded retropie, working properly. Copied git, still working properly. Added install.sh file, still working.  Osd showing. Edit keysKeyboard.cfg, now it stops working. I really am  stuck I'm not sure what to troubleshoot next.

**Comment by withgallantry** [comment]
I'm working on something which should make it a lot easier. Will being able to install this onto an image before burning be any help? You'd just need to change the key configuration then.

**Comment by gh0st08** [comment]
> I'm working on something which should make it a lot easier. Will being able to install this onto an image before burning be any help? You'd just need to change the key configuration then.

It's worth a shot.  How would that work, you would upload the image with it preinstalled and then I burn that to the sd card as  if I am putting retropie on it for the first time?  Sorry if Ive misunderstood.  Otherwise Ill just try whatever you're working on when you're finished. Ill keep trying on my end as well, I am trying to educate myself with all this so I don't miss something obvious.  Thanks again for all of your time and help.

**Comment by Helder1981** [comment]
Ok figured out the issue with the install script, when I press ENTER on the keyboard in a text editor it enters random characters some times for Linux and when the script is read it throws it all off. Here is a fixed and tested install script.
[install-update.zip](https://github.com/withgallantry/OneForAll/files/4079655/install-update.zip)

If you still get an error enter the directory in the FTP browser and open the file and delete some of the empty spaces between the different instructions then put a space between them again. This is so picky now on this newer Retropie that I had to do this to get it to work even when it was copied from another working image that used the exact same install.sh file.

**Comment by gh0st08** [comment]
> Ok figured out the issue with the install script, when I press ENTER on the keyboard in a text editor it enters random characters some times for Linux and when the script is read it throws it all off. Here is a fixed and tested install script.
> [install-update.zip](https://github.com/withgallantry/OneForAll/files/4079655/install-update.zip)
> 
> If you still get an error enter the directory in the FTP browser and open the file and delete some of the empty spaces between the different instructions then put a space between them again. This is so picky now on this newer Retropie that I had to do this to get it to work even when it was copied from another working image that used the exact same install.sh file.

Your install.sh worked fine, osd showing and buttons functioning.  The minute I make a change to the keysKeyboard.cfg though and reboot it stops working all together.  I want to confirm the order of operations here, as I've tried several variations.  Copy git, add install.sh, run install from instructions on your page, edit keysKeyboard.cfg, reboot.  I am using a mac to work from, so to edit keysKeyboard.cfg I'm using terminal- nano keysKeyboard.cfg, edit file and save.  I also added 2 buttons, and have tried what you suggested about adding a button when defining keys to reserve for OSD.  I also tried deleting and reinserting spaces in the keysKeyboard.cfg file.  Ive also tried copying git, editing keysKeyboard.cfg, adding install.sh, and running.  Nothing.  Is there anything obviously wrong that I am doing here that would explain this error?  It's seeming to me that the keysKeyboard.cfg is where all of my issues are originating.  Do I need to make a change in another file as well if I make an edit there?

**Comment by Helder1981** [comment]
The install.sh is just to get everything working and installed now when you make an edit it's probably best to post YOUR keys file here and we can see where the problem is. More than likely there is something there that is conflicting or not set properly. Forget about everything else in your post if it installed properly the first time, we just need the keysKeyboard.cfg you are using.

**Comment by gh0st08** [comment]
> The install.sh is just to get everything working and installed now when you make an edit it's probably best to post YOUR keys file here and we can see where the problem is. More than likely there is something there that is conflicting or not set properly. Forget about everything else in your post if it installed properly the first time, we just need the keysKeyboard.cfg you are using.

I just wiped SD and rewrote image on it.  Maybe there was too much messing around with it before.  This run I changed the the OSD key from gpio pin from 11 to 5, I'm suspecting this could have been a cause of the issues I was running into. OSD is showing, however when I press select to trigger the hot keys the menu doesn't appear like it did before. Buttons still aren't functioning correctly.

Here's what I am using for keys:
[KEYS]
KEY_LEFT=23 #Left DPAD
KEY_RIGHT=18 #Right DPAD
KEY_DOWN=4 #Down DPAD
KEY_UP=15 #Up DPAD
KEY_LEFTCTRL=19 #A Button
KEY_LEFTALT=26 #B Button
KEY_Z=13 #X Button
KEY_X=6 #Y Button
KEY_G=7 #L1 Button
KEY_H=12 #R1 Button
KEY_SPACE=17 #Select Button
KEY_ENTER=22 #Start Button
KEY_B=21 #L2 Button
KEY_N=20 #R2 Button
KEY_U=5 #OSD

[COMBOS]
KEY_ESC=6, 13

[HOTKEYS]
OSD_SHOW=5
VOLUME_UP=15
VOLUME_DOWN=4
TOGGLE_WIFI=23
TOGGLE_BLE=13
TOGGLE_JOYSTICK=19

[JOYSTICK]
ENABLED=False
DEADZONE=300
VCC=1600

**Comment by Helder1981** [comment]
Remap the Buttons in Emulation Station and this should be resolved. But the hot keys menu you mean is the one to get into the Retroarch menu? Also did you change the Retroarch settings for controls like I posted earlier in this thread?

**Comment by gh0st08** [comment]
> Remap the Buttons in Emulation Station and this should be resolved. But the hot keys menu you mean is the one to get into the Retroarch menu? Also did you change the Retroarch settings for controls like I posted earlier in this thread?

I am unable to configure in Emulation Station since the buttons aren't all working. Some of them work others do not.  Do you suspect this is a hardware or software issue that I'm running in to?

**Comment by Helder1981** [comment]
You guys make this harder than it has to be, use a usb controller or a usb keyboard then navigate the menus and when it says to press a button on the keyboard to enter the Remap Menu hold down a button that is working and go from there.

**Comment by gh0st08** [comment]
> You guys make this harder than it has to be, use a usb controller or a usb keyboard then navigate the menus and when it says to press a button on the keyboard to enter the Remap Menu hold down a button that is working and go from there.

I understand what you're saying, but the issue is that half of the buttons aren't being recognized. I already used a keyboard to enter the remap menu, and half the buttons won't register.  If you're not seeing anything wrong with my keys.cfg then it must be a hardware issue.  I may just rip it apart completely and start from scratch.

**Comment by Helder1981** [comment]
Do all of your buttons go to the actual GPIO you are calling in the Keys file? from what I see it looks good but wiring I have no idea.

**Comment by gh0st08** [comment]
> Do all of your buttons go to the actual GPIO you are calling in the Keys file? from what I see it looks good but wiring I have no idea.

I've reverified all buttons are going to GPIO that I am calling in the keys file.  Ive also reverified that I have continuity of each button when button is pressed via a multimeter.  But for whatever reason when I go to map the buttons in Emulation Station all buttons work except for Down, A, R1, and L2.  This has to be a hardware issue at this point right?  But it's strange because I have continuity with the buttons and GPIO.  And to answer your  question from a couple posts ago, the hot key menu I was referring to was the menu that pops up that shows the combination of buttons to press for Volume + -, wifi, joystick, and bluetooth.  This would appear before I made any edits to the keysKeyboard.cfg

**Comment by VeteranGamer** [comment]
> 
> 
> I'm working on something which should make it a lot easier. Will being able to install this onto an image before burning be any help? You'd just need to change the key configuration then.

Just wondering if you got a chance to have a look at the installation
i know you guys have been busy...

but I've never got this to work


thanks

**Comment by Helder1981** [comment]
> 
> 
> > I'm working on something which should make it a lot easier. Will being able to install this onto an image before burning be any help? You'd just need to change the key configuration then.
> 
> Just wondering if you got a chance to have a look at the installation
> i know you guys have been busy...
> 
> but I've never got this to work
> 
> thanks

I got mine to work almost flawlessly and I have been installing it fresh from a new Retreopie Install. There will always be an issue if you have your wiring and pins not labeled right. Hit me up on Discord and I can help you out.

**Comment by gh0st08** [comment]
> > I'm working on something which should make it a lot easier. Will being able to install this onto an image before burning be any help? You'd just need to change the key configuration then.
> 
> Just wondering if you got a chance to have a look at the installation
> i know you guys have been busy...
> 
> but I've never got this to work
> 
> thanks

Hey Veteran, did you ever get your build working?

**Comment by Helder1981** [comment]
> 
> Hey Veteran, did you ever get your build working?

He did get it working it turns out he was using a GPIO for the menu button that was not declared in the list of buttons above in the buttons. Here is my files for reference, basically any GPIO being called anywhere has to be called out in the list of buttons or it will fail.


[keysKeyboard.zip](https://github.com/withgallantry/OneForAll/files/4302705/keysKeyboard.zip)

**Comment by VeteranGamer** [comment]
> 
> 
> > Hey Veteran, did you ever get your build working?

Hi,

Thanks....
I got the OSD to work from another assigned Button
this was also a mistake/school boy error from me, for NOT paying attention and reading this comment section properly as you did clearly advise of what to do earlier...

But the keyKeyboard you provide did the trick....

the next issue I'm facing at the moment is getting the controls to work within Retroarch...

I've followed this 
https://www.retro-programming.de/retro-welt-2/hardware/raspberry-pi-als-emulator-retropie/retropie-controller-einrichten/#manuell

and nothing....

the controls work perfectly fine in Emulation Station....
I've also re-configured the controls again within Emulation Station, once everything was installed 
(and the OSD and Shutdown were working from their respective buttons)

but the controls just to work when in Retroarch
(and obviously in emulation when starting a game)

<a href="https://imgur.com/IVkxDlI"><img src="https://i.imgur.com/IVkxDlI.jpg" title="source: imgur.com" /></a>

the button presses just don't register when going to set Bind
I can press and nothing happens...
however the controls are set in Retroarch as to how I have my controls/keyboard
(this may have been set when Emulation Station was configured)


the GPIO and the buttons work and are functioning because the work perfectly fine within Emulation Station....

but not in Retroarch


setup: RPi3A+ running RetroPie 4.5.1 image (from official RetroPie Site)
system has been tested as is....
also with updating RetroPie setup script
and by also updating core (but these shouldn't make any difference)



it is what it is....
I know you guys are busy with the next batch of products your are releasing....
so just didnt want to bother you

**Comment by Helder1981** [comment]
I've mentioned this in the messages above you need to use another control method like a keyboard or edit the file that has the default retroarch.cfg to make the controls as linuxraw. Right now it's udev but for whatever reason it won't recognize the buttons unless you change it to linuxraw. Here is the link to how to maneuver through the menus to change it with a keyboard or something else.

https://www.retro-programming.de/retro-welt-2/hardware/raspberry-pi-als-emulator-retropie/retropie-controller-einrichten/#manuell

**Comment by VeteranGamer** [comment]
> 
> 
> I've mentioned this in the messages above you need to use another control method like a keyboard or edit the file that has the default retroarch.cfg to make the controls as linuxraw.
>
thats my bad.... 
clearly reading isn't my strong suit (still trying to work out what my strong suit is)

everything works as it should.... **Thank you (really appreciate the patience and the help)**

just for any other NOOB out there (it may just be me)....
and to clarify what I did
download
https://github.com/withgallantry/OneForAllBinary
rename the folder to OneForAll using FileZilla

extract the install.sh and move it to the OneForAll folder (again using FileZilla
[install.zip](https://github.com/withgallantry/OneForAll/files/4311379/install.zip)

now enter Terminal either by exiting Emulation Station (keyboard needed) or SSH (putty)
and then install/enable
$ sudo chmod 755 /home/pi/OneForAll/install.sh
$ sudo /home/pi/OneForAll/./install.sh

Restart 
and the battery icon should now show up along with other icons....

controls can now be configured (via Terminal or Filezilla)
$ sudo nano /home/pi/OneForAll/keysKeyboard.cfg

If the Show OSD isn't going to be different to the Hotkey (select)
then just edit the current keysKeyboard.cfg and you should be good, make sure the GPIO are correct
(also make sure that your Shutdown corresponds with the general.cfg)

if like me you decided to have a separate button for the OSD 
then add this to you keysKeyboard.cfg and edit according to your setup

KEY_U=23 #Needed to Work with OSD

[keysKeyboard.zip](https://github.com/withgallantry/OneForAll/files/4311664/keysKeyboard.zip)

after this you should have working controls within Emulation Station

for RPi3A/B then a configuration of the input binds in RetroArch is also needed
instructions can be found here
https://www.retro-programming.de/retro-welt-2/hardware/raspberry-pi-als-emulator-retropie/retropie-controller-einrichten/#manuell

once this has been done...
you just need to edit the retroarch.cfg and replace udev with linuxraw for the input driver
input_driver = "linuxraw"
i also edited/changed
input_joypad_driver = "linuxraw"

retroarch.cfg can be accessed/edited in a number of ways
via terminal
$ sudo nano /opt/retropie/configs/all/retroarch.cfg
via Filezilla or Samba on your Network from your PC/Laptop


this should be it...
and everything should be working....


**NB: ALL THIS HAS ALREADY BEEN EXPLAINED/ADVISED BY HELDER IN THE PREVIOUS POSTS**  

.

**Comment by caver01** [comment]
Would I be able to follow these instructions for updating my MintyPi v3? While it works as-is, I want to configure an ESC key combo so I can explore using dedicated emulators, but don't want to break my setup.

**Comment by VeteranGamer** [comment]
> 
> 
> Would I be able to follow these instructions for updating my MintyPi v3? While it works as-is, I want to configure an ESC key combo so I can explore using dedicated emulators, but don't want to break my setup.

**these instructions are NOT for the mintyPi**

however it may be possible to assign a combo to initiate a ESC key press...
if one already isn't present

there used to be a combo on previous mintyPi, not sure if the V3 has this
Select + B

**your best bet is to double check with Helder**

but if you are able to add a combo, it may look something like this....

<a href="https://imgur.com/cmu8FS1"><img src="https://i.imgur.com/cmu8FS1.jpg" title="source: imgur.com" /></a>

but you'd still need to check with someone more knowledgeable as to 
if its possible
and if possible how and what to put in the .cfg **(im only guessing)**

**CHECK WITH HELDER BEFORE MAKING ANY CHANGES**
