### ISSUE TITLE
Can't Complete the OneForAll Install

### ISSUE THREAD

**Issue by Unboundclassic** [withgallantry/OneForAll#6]
**I contacted Helder about going from the old version of OneForAll to the new one and he pointed me to your OneForAll source instead of his and he provided these instructions as yours seem to be incomplete:**

_Ok I can give you some instructions, first do a fresh install by deleting or renaming the old folder then run:
git clone --recursive https://github.com/withgallantry/OneForAll.git
then
cd OneForAll
make
sudo chmod 755 /home/pi/OneForAll/monitor.py
sudo chmod 755 /home/pi/OneForAll/osd/osd
sudo chmod 755 /home/pi/OneForAll/rfkill/rfkill

Place attached file in the folder OneForAll then run this:

cp -r /home/pi/OneForAll/oneforall.service /etc/systemd/system/oneforall.service
sudo systemctl enable oneforall.service
sudo systemctl start oneforall.service

after that you need to install some other required software using the following commands as one single command :
sudo apt-get update && sudo apt-get install python-gpiozero python-pkg-resources python3-pkg-resources build-essential python-dev python-smbus python-pip i2c-tools raspi-gpio i2c-tools wiringpi libi2c-dev libudev-dev libcaca-dev python-serial && sudo pip install adafruit-ads1x15 wiringpi2 configparser python-uinput

then reboot using sudo reboot -h now everything should be working but you will need to configure the keysKeyboard.cfg and general.cfg_

**There were a few hiccups, but I got to the bottom where you install the long string of required software. I can't seem to get it to complete. Tried a few times. It's finishing anything past the adafruit-adslx15. I tried running the Pi but OneForAll is not showing up at all so obviously I'm missing something. This is what I'm getting:** 
![Screenshot from 2020-05-09 22-32-24](https://user-images.githubusercontent.com/49640762/81491136-a6faa980-9247-11ea-8194-c1952e250ae3.png)

I'm happy to start over if this is all way off.

**Comment by Unboundclassic** [comment]
Side note... somehow what I did here also has affected my i2s audio board... I don't have sound anymore... hmmm

**Comment by Unboundclassic** [comment]
**So here's the fresh install steps I took talking with Helder. The install seemed to work..... except that nothing works, lol.**  

git clone --recursive https://github.com/withgallantry/OneForAll.git
then
cd OneForAll
make
sudo chmod 755 /home/pi/OneForAll/monitor.py
sudo chmod 755 /home/pi/OneForAll/osd/osd
sudo chmod 755 /home/pi/OneForAll/rfkill/rfkill

cd ~
git clone https://github.com/adafruit/Adafruit_Python_ADS1x15.git
cd Adafruit_Python_ADS1x15
sudo python setup.py install

sudo shutdown

Place attached file (oneforall.service) in the folder OneForAll then run this:

sudo chmod 777 /etc/systemd/system
cp -r /home/pi/OneForAll/oneforall.service /etc/systemd/system/oneforall.service
sudo chmod 755 /etc/systemd/system
sudo systemctl enable oneforall.service
sudo systemctl start oneforall.service

after that you need to install some other required software using the following commands as one single command :

sudo apt-get update && sudo apt-get install python-gpiozero python-pkg-resources python3-pkg-resources build-essential python-dev python-smbus python-pip i2c-tools raspi-gpio i2c-tools wiringpi libi2c-dev libudev-dev libcaca-dev python-serial && sudo pip install adafruit-ads1x15 wiringpi2 configparser python-uinput

sudo apt-get update

sudo nano /boot/config.txt
be sure dtparam=i2c_arm=on is not commented out by removing the # in front of it

next type

sudo nano /etc/modules

add these 2 lines
i2c-bcm2708
i2c-dev 

then reboot using sudo reboot -h 

sudo shutdown

Configure the keysKeyboard.cfg and general.cfg to the desired inputs

cd OneForAll

After that try to run the software while you are in the OneForAll folder by using  sudo ./monitor.py you might want to fix your buttons before that though and also in the general.cfg too if it has errors then we can try to figure what they are. 
 
Trying that last command I get this returned:
![sudo monitor py](https://user-images.githubusercontent.com/49640762/82644678-f1c4db80-9bce-11ea-8112-bf95e08c3812.png)

**Comment by Unboundclassic** [comment]
A couple observations:

- The old version of OneForAll had a the line in the file etc/rc.local that read /home/pi/OneForAll/monitor < /dev/zero &> /dev/null & I assume this was the line to start up the old script on boot. After the new install I just looked and there is no such line in the rc.local file. So essentially it doesn't look like the script is launching at all. Which lines up with what I'm experiencing. After that first try I have not been able to get ES to recognize any inputs at all from OneForAll. It's like it's not there at all. I tried putting the old script activation line into the rc.local file and I also tried the line "sudo python /home/pi/OneForAll/monitor.py &" in an attempt to activate the script. No luck. I took those lines back out of rc.local after they didn't work.

- Alternatively (or in addition), and this could just be my ignorance to the programing language, but it seems like the monitor.py script is still set up to reference the old keys.cfg file naming from the old OneForAll. When I opening the script and searching there are only references to keysConfig and no references to keysGamepadConfig or anything like that. It seems like it wouldn't be able to find when written out like it is. But I could be way off on this one.

**Comment by Unboundclassic** [comment]
**OK, here's how we fixed it.**

---------------

Erase everything in the OneForAll folder but keep the keys file so you can just copy over the button pinout and run these don't forget the oneforall.service:

git clone --recursive https://github.com/withgallantry/OneForAll.git
cd OneForAll
make

sudo chmod 755 /home/pi/OneForAll/monitor.py
sudo chmod 755 /home/pi/OneForAll/osd/osd
sudo chmod 755 /home/pi/OneForAll/rfkill/rfkill

sudo shutdown -h now
placed the oneforall.service file in  /home/pi/OneForAll/

Booted back up and went to command line.

cp -r /home/pi/OneForAll/oneforall.service /etc/systemd/system/oneforall.service
sudo systemctl enable oneforall.service
sudo systemctl start oneforall.service


sudo apt-get update && sudo apt-get install python-gpiozero python-pkg-resources python3-pkg-resources build-essential python-dev python-smbus python-pip i2c-tools raspi-gpio i2c-tools wiringpi libi2c-dev libudev-dev libcaca-dev python-serial && sudo pip install wiringpi2 configparser python-uinput


sudo nano /boot/config.txt
be sure dtparam=i2c_arm=on is not commented out by removing the # in front of it

sudo nano /etc/modules

***add these 2 lines***
i2c-bcm2708
i2c-dev

sudo rm -rf /usr/local/lib/python2.7/dist-packages/Adafruit_PureIO
git clone https://github.com/withgallantry/Adafruit_Python_ADS1x15
cd Adafruit_Python_ADS1x15
sudo python setup.py install
sudo reboot -h

BUT that didn't quite finish it.

The fresh install got me most of the way there. I figured out what was happening before. Not sure why this happens... but I found my way around it so I hope this helps.

By default it appears that the script is set to use keysKeyboard.cfg as its Keys reference. But wasn't this made for mostly portable builds? So why not default to keysGamepad.cfg? BUT the trouble happens if I tried to edit the keysKeyboard.cfg file to match my GPIO pin out. If I changed the numbers and then booted up, the on screen display would not be there and no input would be available. Odd. This is what was happening before when nothing would show up. I then checked it by changing the GPIO numbers back to default and booted up. The OSD and input option came back.

So, I was not aware that in the general.cfg file there was an option to change the keys reference to keysGamepad.cfg instead. Please mention this important info in the new Readme. I did and saved it and then edited that file for my GPIO pin out and booted up. Success! The OSD is there, the input was detected, and the configuration worked for the keys and joystick.

The controls are back in business! It's nice I have the option now to have the hotkey separate from the select key so it doesn't flash every time I hit select like it did in the old version.

**Comment by Unboundclassic** [comment]
I've fixed my issue but it would be good to take a look at my last comment and the issues that still exist there.

**Comment by DoomyDoomer** [comment]
@Unboundclassic I’m not seeing any attachment for OneForAll.service. Do you have handy somewhere?

**Comment by Helder1981** [comment]
[oneforall.service.zip](https://github.com/withgallantry/OneForAll/files/5209077/oneforall.service.zip)
